import { Sidebar } from '@share/components/layout'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Sidebar />
      <body>{children}</body>
    </html>
  )
}
